config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get  'welcome',  to: 'welcome#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  def self.show_stock
  	looked_up_stock      = StockQuote::Stock.quote('GOOG')
  	new_stock            = Stock.new
  	new_stock.ticker     = "#{looked_up_stock.symbol}"
  	new_stock.name       = "#{looked_up_stock.name}"
  	new_stock.last_price = new_stock.price

  	return new_stock
  end

  def self.search_stock(ticker)
  	if !(ticker=="")
  		looked_up_stock      = StockQuote::Stock.quote(ticker)
  		#return nil unless looked_up_stock.name

  		new_stock            = Stock.new
  		new_stock.ticker     = "#{looked_up_stock.symbol}"
  		new_stock.name       = "#{looked_up_stock.name}"
  		new_stock.last_price = new_stock.price
    else
    	new_stock            = Stock.new
  		new_stock.ticker     = "N/A"
  		new_stock.name       = "N/A"
  		new_stock.last_price = -1

    end


  	return new_stock
  end

  def price
  	closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price
    
    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price

    return 'Unavailable'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@stock = Stock.search_stock(params[:stock])
  	#@stock.name = "no"
    #@stock.ticker = "nono"
    #@stock.last_price = -1
    if @stock
      #render json: @stock
      #render partial: 'lookup'
      
    else
      #render  status: :not_found, nothing: true
      
    end
  end

  def search

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StockSample" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">StockSample</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

      <footer>
        <p>&copy; Jim 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Stock Sample</h1>

<%= form_tag welcome_path, method: :get, id: 'search-form' do %>
  <p>
    <%= text_field_tag :stock, params[:stock] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<p>
  <strong>Stock:</strong>
  <%= @stock.name %>
  <%= @stock.ticker %>
  <%= @stock.last_price %>
</p>

<%= link_to "logout", destroy_user_session_path, method: :delete%>